package com.sansux.boss.mapper;

import com.sansux.boss.bo.Product;
import com.sansux.boss.bo.ProductBo;
import com.sansux.boss.bo.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `product` (`id`, `name`, ",
        "`price`, `seller_id`, ",
        "`img`, `flag`, `description`, ",
        "`abstracts`, `create_time`, ",
        "`update_time`, `sell_num`, ",
        "`deleted`)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{sellerId,jdbcType=INTEGER}, ",
        "#{img,jdbcType=VARCHAR}, #{flag,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{abstracts,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{sellNum,jdbcType=INTEGER}, ",
        "#{deleted,jdbcType=VARCHAR})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `name`, `price`, `seller_id`, `img`, `flag`, `description`, `abstracts`, ",
        "`create_time`, `update_time`, `sell_num`, `deleted`",
        "from `product`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    @Update({
        "update `product`",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "`price` = #{price,jdbcType=DECIMAL},",
          "`seller_id` = #{sellerId,jdbcType=INTEGER},",
          "`img` = #{img,jdbcType=VARCHAR},",
          "`flag` = #{flag,jdbcType=VARCHAR},",
          "`description` = #{description,jdbcType=VARCHAR},",
          "`abstracts` = #{abstracts,jdbcType=VARCHAR},",
          "`create_time` = #{createTime,jdbcType=TIMESTAMP},",
          "`update_time` = #{updateTime,jdbcType=TIMESTAMP},",
          "`sell_num` = #{sellNum,jdbcType=INTEGER},",
          "`deleted` = #{deleted,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);

    List<Product> selectByBuyer(Integer userId);

    Product selectByNameAndNotId(Product product);

    List<Product> shoppingCart(Integer userId);

    List<Product> bill(Integer userId);

    Product checkProductBuy(Integer productId, int userId);

    ProductBo selectByProductIdAndUserId(int productId, int userId);

    void joinShoppingCart(int productId, int userId, String flag, int count, int i, long price);

    void updateCountAndPrice(int id, int finalCount, long price);

    void moveFromShoppingCart(Integer id);

    List<ProductBo> findProductId(@Param("idList") List<Integer> idList);

    void buyProduct(@Param("idList") List<Integer> idList);

    void sellNumAutoIncrement(@Param("idList") List<ProductBo> productIdList);

    void editProduct(Product product);

    void deleteById(Integer id);

    List<Product> selectByBuyerNotBuy(Integer userId);
}